enforce-work-item-for-pr: true
core-deploy:
  enabled: true
  use-core-packager: false
steps:
  node-build:
    env:
      NODE_OPTIONS: "--max_old_space_size=7680"
  node-pre-release-tests:
    run:
      command: yarn test:unit:coverage
  platform-build:
    name: platform-build
    description: Runs platform-specific build step
    run:
      command: yarn release:corejar
    before: core-packager
