enforce-work-item-for-pr: true
core-deploy:
  enabled: true
  use-core-packager: false
steps:
  node-build:
    env:
      NODE_OPTIONS: '--max_old_space_size=1024'
    run:
      command: yarn build:nucleus
  node-pre-release-tests:
    run:
      command: yarn test:unit:coverage
  platform-build:
    name: platform-build
    description: Runs platform-specific build step
    run:
      command: yarn release:corejar
    before: core-packager
  code-format-after-dep-patch:
    group: publish
    description: Code formatting fix after package.json dep patching
    run:
      command: yarn format:fix
    after: npm-patch-dependency-versions
notifications:
  email:
    address: auradataservicescrumteam@salesforce.com
  slack:
    channel: lds-notifications
