# Environment configuration
# =========================

env_default: &env_default
  working_directory: ~/lds-lp
  docker:
    - image: circleci/node:10-browsers

env_perf: &env_perf
  <<: *env_default
  environment:
    - GIT_APP_CERT_PATH: ~/lds-lp/git_app.pem

env_test: &env_test
  <<: *env_default
  environment:
    - SAUCE_USERNAME: lwc_ci
    - SAUCE_KEY: ca71d9ad-af28-4c2b-abf7-1ddaa87fed36

# Commands definitions
# ====================

# Yarn cache
restore_yarn_cache: &restore_yarn_cache
  restore_cache:
    keys:
      - yarn-v4-{{ checksum "yarn.lock" }}

save_yarn_cache: &save_yarn_cache
  save_cache:
    key: yarn-v4-{{ checksum "yarn.lock" }}
    paths:
      - ~/.cache/yarn

# Workspace
save_workspace: &save_workspace
  persist_to_workspace:
    root: .
    paths: .

load_workspace: &load_workspace
  attach_workspace:
    at: ~/lds-lp

# Build
install: &install
  run:
    name: Install dependencies
    command: yarn install --frozen-lockfile

# Checks
run_format: &run_format
  run:
    name: Run format
    command: yarn format:check

run_linting: &run_linting
  run:
    name: Run linting
    command: yarn lint

# Test
run_unit_tests: &run_unit_tests
  run:
    name: Run unit tests with coverage
    # Jest should run sequentially instead of parallel on the CI to avoid running out of memory and
    # reduce run duration.
    # https://jestjs.io/docs/en/troubleshooting#tests-are-extremely-slow-on-docker-and-or-continuous-integration-ci-server
    command: yarn test:unit --runInBand --ci --coverage

store_unit_tests_coverage: &store_unit_tests_coverage
  store_artifacts:
    path: coverage

run_integration_tests: &run_integration_tests
  run:
    name: Run integration tests
    command: yarn test:integration

run_integration_tests_compat: &run_integration_tests_compat
  run:
    name: Run integration tests (compat)
    command: yarn test:integration:compat

# Sauce Labs
setup_sauce_env_variables: &setup_sauce_env_variables
  run:
    name: Setup sauce connect environnement variables
    command: echo 'export SAUCE_TUNNEL_ID="lds-${CIRCLE_BUILD_NUM}"' >> $BASH_ENV

start_sauce_connect: &start_sauce_connect
  run:
    name: Install and start sauce connect
    background: true
    command: |
      # Be mindfull when upgrading the version of sauce connect. Saucelabs' support acknowledged that the 4.5.2 and
      # 4.5.3 versions have some issues related to tunnel creation.
      curl https://saucelabs.com/downloads/sc-4.5.1-linux.tar.gz -o saucelabs.tar.gz
      tar -xzf saucelabs.tar.gz
      cd sc-*
      bin/sc -u ${SAUCE_USERNAME} -k ${SAUCE_KEY} -i ${SAUCE_TUNNEL_ID}

wait_for_sauce_connect: &wait_for_sauce_connect
  run:
    name: Wait for sauce connect to be up
    command: wget --retry-connrefused --no-check-certificate -T 60 localhost:4445

stop_sauce_connect: &stop_sauce_connect
  run:
    name: Stop sauce connect
    command: kill -9 `cat /tmp/sc_client-${SAUCE_TUNNEL_ID}.pid`

# Best
setup_best_environment: &setup_best_environment
  run:
    name: Setup BEST environment
    command: echo '
      export PULL_REQUEST=${CIRCLE_PULL_REQUEST}
      export REPO_NAME=${CIRCLE_PROJECT_REPONAME}
      export TARGET_COMMIT=${CIRCLE_SHA1}
      export BASE_COMMIT=`git rev-parse origin/master`' >> $BASH_ENV

      echo -e "$GIT_APP_CERT" | base64 -d >> ~/lds-lp/git_app.pem

run_best: &run_best
  run:
    name: Run performance Test
    command: yarn test:perf --projects best.config.js --externalStorage=@best/store-aws --runner remote --runInBatch --dbAdapter=sql/postgres --dbURI=${BEST_HUB_DATABASE_URL}

compare_best_results: &compare_best_results
  run:
    name: Comparing perf examples
    command: yarn test:perf --projects best.config.js --compareStats ${BASE_COMMIT} ${TARGET_COMMIT} --externalStorage=@best/store-aws --gitIntegration

store_best_artifacts: &store_best_artifacts
  store_artifacts:
    path: ~/lds-lp/__benchmark_results__/
    destination: benchmarks

test_size: &test_size
  run:
    name: Run bundle size check
    command: yarn test:size

test_memory: &test_memory
  run:
    name: Run memory perf test
    command: yarn test:memory

# Jobs definition
# ===============

version: 2
jobs:
  build_and_test:
    <<: *env_default
    steps:
      - checkout

      - *restore_yarn_cache
      - *install
      - *save_yarn_cache

      - *save_workspace

      - *run_linting
      - *run_format

      - *run_unit_tests
      - *store_unit_tests_coverage

  test_integration:
    <<: *env_test
    steps:
      - *load_workspace

      - *setup_sauce_env_variables
      - *start_sauce_connect
      - *wait_for_sauce_connect

      - *run_integration_tests
      - *run_integration_tests_compat

      - *stop_sauce_connect

  perf_and_compare:
    <<: *env_perf
    steps:
      - *load_workspace

      - *test_size
      - *test_memory

      - *setup_best_environment
      - *run_best
      # temporary disabled
      #      - *compare_best_results
      - *store_best_artifacts

# Workflows definition
# ====================

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - test_integration:
          requires:
            - build_and_test
      - perf_and_compare:
          requires:
            - build_and_test
